### ISSUE TITLE
Fix static text editor

### ISSUE THREAD

**Issue by huisit** [thepoly/Pipeline#71]
After changing component structure, clicking to see details for a story does not change the text in the live editor.

The URL is routed with the correct ID, and all other details/information in the StoryDetail component change, but the text editor shows the text for the first story, unless the URL is entered/refreshed manually.

**Comment by kochman** [comment]
I think the problem is that the iframe src attribute is changed whenever a different story is selected, but the real-time editor does not change the active document. It currently only does this on document load.

**Comment by kochman** [comment]
Resolved in 42eef0d.
