### ISSUE TITLE
<p> tag is appearing in article text when creating links on facebook

### ISSUE THREAD

**Issue by jlyon1** [thepoly/pipeline#92]

**Comment by bparslow** [comment]
<img width="287" alt="Screen Shot 2019-09-24 at 4 33 04 PM" src="https://user-images.githubusercontent.com/32580841/65548228-0ee2c680-dee9-11e9-9a37-163f4953ebb2.png">

**Comment by stotzjohn** [comment]
When an article doesn't have a summary such as https://poly.rpi.edu/opinion/2019/09/what-the-class-of-2023-wants-to-know/ it doesn't have a problem.
